### ISSUE TITLE
Problem while running the example.sh file in style_decoder/

### ISSUE THREAD

**Issue by brihijoshi** [shrimai/Style-Transfer-Through-Back-Translation#1]
Hey!

I was going through your paper link and trying to set-up the code pipeline.
While running the commands written in your 'example.sh' file in style_decoder/ , I found the following error - 
```
 usage: translate.py [-h] -encoder_model ENCODER_MODEL -decoder_model
                    DECODER_MODEL -src SRC [-tgt TGT] [-output OUTPUT]
                    [-beam_size BEAM_SIZE] [-batch_size BATCH_SIZE]
                    [-max_sent_length MAX_SENT_LENGTH] [-replace_unk]
                    [-verbose] [-n_best N_BEST] [-gpu GPU]
translate.py: error: the following arguments are required: -encoder_model, -decoder_model
```
However, using encoder and decoder models isn't mentioned in the README.md file.

Could you kindly help me with it? Thanks a lot!

**Comment by shrimai** [comment]
Hi,

If you are using the translate.py script to use the style_decoder then you have to use the options of -encoder_model ENCODER_MODEL and -decoder_model DECODER_MODEL. You have to provide the path to the encoder of the French-English MT and the path to the decoder of the style generator you want to use. I will once again have a look at example.sh and change it if necessary. You have to use the -model option only when using the English-French MT.

**Comment by brihijoshi** [comment]
Thank you for helping out!
The code seems to work perfectly now :)
