### ISSUE TITLE
Assertion Error during trying to use gpus of train_decoder.py

### ISSUE THREAD

**Issue by g22gs** [shrimai/Style-Transfer-Through-Back-Translation#15]
Hi,
I am following commands in style_decoder/example.sh and come to this line

> python train_decoder.py -data ../data/democratic_generator.train.pt -save_model trained_models/democratic_generator -classifier_model ../models/classifier/political_classifier/political_classifier.pt -encoder_model ../models/translation/french_english/french_english.pt -tgt_label 1

It seems working fine but when I try to use gpu, the following command:

> python train_decoder.py -data ../data/democratic_generator.train.pt -save_model trained_models/democratic_generator -classifier_model ../models/classifier/political_classifier/political_classifier.pt -encoder_model ../models/translation/french_english/french_english.pt -tgt_label 1 -gpus 0

gives me error message:

> Namespace(batch_size=64, brnn=True, brnn_merge='concat', class_weight=1.0, classifier_model='../models/classifier/political_classifier/political_classifier.pt', curriculum=False, data='../data/democratic_generator.train.pt', dropout=0.3, encoder_model='../models/translation/french_english/french_english.pt', epochs=13, extra_shuffle=False, gpus=[0], input_feed=1, layers=2, learning_rate=1.0, learning_rate_decay=0.5, log_interval=50, max_generator_batches=32, max_grad_norm=5, nll_weight=1.0, optim='sgd', param_init=0.1, pre_word_vecs_dec=None, pre_word_vecs_enc=None, rnn_size=500, save_model='trained_models/democratic_generator', sequence_length=50, start_decay_at=8, start_epoch=1, temperature=1.0, tgt_label=1, train_from='', train_from_state_dict='', word_vec_size=300)
> Loading data from '../data/democratic_generator.train.pt'
>  * vocabulary size. source = 100004; target = 20004
>  * number of training sentences. 260170
>  * maximum batch size. 64
> Loading Encoder Model ...
> Loading CNN Classifier Model ...
> Building model...
> Traceback (most recent call last):
>   File "train_decoder.py", line 437, in <module>
>     main()
>   File "train_decoder.py", line 387, in main
>     encoder.cuda()
>   File "/home/kouhakuken0609/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 216, in cuda
>     return self._apply(lambda t: t.cuda(device))
>   File "/home/kouhakuken0609/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
>     module._apply(fn)
>   File "/home/kouhakuken0609/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 123, in _apply
>     self.flatten_parameters()
>   File "/home/kouhakuken0609/anaconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 111, in flatten_parameters
>     params = rnn.get_parameters(fn, handle, fn.weight_buf)
>   File "/home/kouhakuken0609/anaconda3/envs/py36/lib/python3.6/site-packages/torch/backends/cudnn/rnn.py", line 165, in get_parameters
>     assert filter_dim_a.prod() == filter_dim_a[0]
> AssertionError

Using python 3.6, PyTorch 0.3.1 and cuda80
Any tips would be appreciated. Thanks

**Comment by shrimai** [comment]
Some of these[ links](https://github.com/pytorch/pytorch/issues/5667) say that it is the issue with PyTorch 0.3.1. Reinstall pytorch with version 0.3.0, python 3.6 and cuda80 and then try.

**Comment by g22gs** [comment]
> Some of these[ links](https://github.com/pytorch/pytorch/issues/5667) say that it is the issue with PyTorch 0.3.1. Reinstall pytorch with version 0.3.0, python 3.6 and cuda80 and then try.
It works fine now. Thank you.
