### ISSUE TITLE
Preprocessing pipelines for translation models

### ISSUE THREAD

**Issue by bywords** [shrimai/Style-Transfer-Through-Back-Translation#18]
Hi, thank you for developing and releasing the model for wider usage. 

I'm trying to apply your model to my task, and I'm just wondering what kinds of preprocessing techniques were applied to the input of your translation models. What kinds of tokenizers were used, and how were named entities handled? 

Thanks in advance.

**Comment by shrimai** [comment]
I used moses tokenizer for both english and french languages. I convert everything to lower case. Named entities were not handled any differently. After I create a vocabulary, I replace the words not in the vocab with <UNK> token.

**Comment by bywords** [comment]
Thank you for your response. One last question.. Did you also leave digits and special characters as unchanged?

**Comment by shrimai** [comment]
Yes, I left them unchanged.

**Comment by abhirut** [comment]
Hi,

Thanks for releasing the trained models. I was also trying to use the translation model for my task. I am not seeing the BLEU score from the paper - 32.52 on the English-French Newstest 2014 task.

Could you kindly help me with the test set that you evaluated this model on? I think I might be making some mistake with the pre-processing.

I am lowercasing both source and target files and then tokenizing with the moses tokenizer perl script. Finally, I'm computing BLEU with the `multi-bleu.perl` script.

**Comment by abhirut** [comment]
Sorry for the trouble, got my answer - WMT 2015.

Any comments on the steps would be helpful. The translation command I use is - 
```
python translate.py \
  -gpu 0 \
  -model <path> \
  -src <path> \
  -output <path>
```
