### ISSUE TITLE
Incredibly high perplexity with Translator_Style 

### ISSUE THREAD

**Issue by chejmadi** [shrimai/Style-Transfer-Through-Back-Translation#20]
We're getting results with an Average score of -6.4762 and a prediction perplexity of 649.4811 while translating the republican test set (from French to English) for style generation (the last line in example.sh). We are using the best model downloaded in models/style_generator. What is the reason for this?

**Comment by shrimai** [comment]
These are summation of beam search scores for all tokens. If you want to report perplexity, then you should use some other toolkits.
