### ISSUE TITLE
cannot download data

### ISSUE THREAD

**Issue by apple024** [shrimai/Style-Transfer-Through-Back-Translation#23]
Hello, I try to download the political_data via:
wget http://tts.speech.cs.cmu.edu/style_models/political_data.tar
However, the url can't be reached with information:
connecting to tts.speech.cs.cmu.edu... failed: connection timed out
could you please help me with it?

**Comment by shrimai** [comment]
It looks like I can download the data and the server is up. Could you please try again?

**Comment by apple024** [comment]
it works now. many thanks!
