### ISSUE TITLE
Sentiment Transfer Error

### ISSUE THREAD

**Issue by SOURO** [shrimai/Style-Transfer-Through-Back-Translation#25]
**Running:**
`python translate.py -encoder_model ../models/translation/french_english/french_english.pt -decoder_model ../models/style_generators/positive_generator.pt -src ../data/sentiment/yelp/sentiment.test.0.fr -output neg_pos.txt -replace_unk $true`

**Error:**
`Traceback (most recent call last):
  File "translate.py", line 139, in <module>
    main()
  File "translate.py", line 66, in main
    translator = onmt.Translator_style(opt)
  File ... /Style-Transfer-Through-Back-Translation/style_decoder/onmt/Translator_style.py", line 22, in __init__
    decoder.load_state_dict(checkpoint['decoder'])
  File  ... /Style-Transfer-Through-Back-Translation/venvs/env_backtran/lib/python3.6/site-packages/torch/nn/modules/module.py", line 519, in load_state_dict
    .format(name, own_state[name].size(), param.size()))
RuntimeError: While copying the parameter named word_lut.weight, whose dimensions in the model are torch.Size([9603, 300]) and whose dimensions in the checkpoint are torch.Size([9603, 100]).
`
Please help ...
**I am using the same python and pytorch version in this repository**

**Comment by SOURO** [comment]
actually what I have understood is:

300 is coming from the saved encoder model (pretrained model fr-rn model) ...
https://github.com/shrimai/Style-Transfer-Through-Back-Translation/blob/master/style_decoder/onmt/Translator_style.py  line number 21 ... 
but line number 22: saved decoder model checkpoint is expecting 100 dimensions ... hence this error (possibly) ... if this is true, then can you please provide me the correct (I mean synced) model? Thank you

**Comment by shrimai** [comment]
This seems like a mismatch of word embedding sizes. You are loading a checkpoint which has word embedding size 100 but the code expects it to be 300.
The enc_opt at https://github.com/shrimai/Style-Transfer-Through-Back-Translation/blob/e6ecdd0a0a3f30b5e5efc0ab55b01443c7019144/style_decoder/onmt/Translator_style.py#L21
 has word embedding size 300. You would have to change that. Either explicitly change the variale value and then pass it at that line or make a separate decoder_opt with correct values.

**Comment by SOURO** [comment]
Thank you for your quick reply ...
yes ... I understood this is a mismatch of word embedding sizes ... 

I am using your provided(pre trained) fr-en encoder model and postive generator decoder model ....

so it seems postive gen model has embedding size 100 ...

I explicitly changed it to 100, but then getting below error:
`raise KeyError('missing keys in state_dict: "{}"'.format(missing))
KeyError: 'missing keys in state_dict: "{\'rnn.layers.1.bias_hh\', \'rnn.layers.1.weight_ih\', \'rnn.layers.1.bias_ih\', \'rnn.layers.1.weight_hh\'}"'`

**Comment by SOURO** [comment]
Using the generator from the below location:
http://tts.speech.cs.cmu.edu/style_models/positive_generator.tar

**Comment by shrimai** [comment]
The file at that location should be correct.
As a sanity check that you have completely downloaded the file, you can print the keys of the state_dict and check.
At this moment I am unable to ping tts.speech.cs.cmu.edu machine and hence if you downloaded in the last hour maybe you have not downloaded the complete file. I will check and let you know when tts will be back up.
enc_opt must be changed to dec_opt = checkpoint['opt'] at https://github.com/shrimai/Style-Transfer-Through-Back-Translation/blob/e6ecdd0a0a3f30b5e5efc0ab55b01443c7019144/style_decoder/onmt/Translator_style.py#L21

**Comment by SOURO** [comment]
Thank you ... 
I have changed ...
I got the output ... 
Can you please update `dec_opt = checkpoint['opt']; decoder = onmt.Models_decoder.Decoder(dec_opt, self.tgt_dict)` in this code rep?

**Comment by SOURO** [comment]
Thank you @shrimai for your kind replies ... 
I am doing research on controllable language generation (currently on style transfer) ...
I have few observations regarding this work and my work (inline with this work of yours) ...
I know you will be very busy but still can I mail you to discuss the same(if your time permits)? Thank you ...

**Comment by SOURO** [comment]
Also as I can see negative to positive style transfer has happened but content and structure loss of the source sentence in heavy ... hence PPL is very high ... can you please share your view on the same?

**Comment by shrimai** [comment]
Sure, you can email me: sprabhum @ alumni.cmu.edu
