### ISSUE TITLE
Unavailability of rebublican_only.test.fr

### ISSUE THREAD

**Issue by justachetan** [shrimai/Style-Transfer-Through-Back-Translation#3]
Hi!

I was trying to run the ```style_decoder/example.sh``` script and ran into a problem.

The last line of ```style_decoder/example.sh``` is:

```
python translate.py -encoder_model ../models/translation/french_english/french_english.pt -decoder_model ../models/style_generators/democratic_generator.pt -src ../data/political_data/republican_only.test.fr -output trained_models/republican_democratic.txt -replace_unk $true
```

However, in the ```README.md```, there is no mention of how to obtain the file **rebublican_only.test.fr**. 

Could you please share how can I obtain this file?

**Comment by shrimai** [comment]
The republican_only.test.fr file can be generated from the  republican_only.test.en file using the translate.py script. The example of how to use this script is given in the example.sh script.
